# Generated by Django 2.2.3 on 2019-07-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emaildata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('sender', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('from_email', models.EmailField(max_length=254, verbose_name='email отправителя')),
                ('subject', models.CharField(max_length=128, verbose_name='Тема')),
                ('body', models.TextField(max_length=256, verbose_name='Письмо')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
            ],
        ),
    ]
